services:
  ntfy-client:
    container_name: ntfy-client
    image: binwiederhier/ntfy:latest
    entrypoint: "ntfy"
    command: "sub -c /etc/ntfy/client.yml -C"
    environment:
      - TZ=${CONTAINER_TZ}
    user: 1000:1000
    volumes:
      - type: bind
        source: ./../Docker-data/Notifications/Ntfy/data
        target: /etc/ntfy
    restart: unless-stopped

  ntfy-server:
    container_name: ntfy-server
    image: binwiederhier/ntfy:latest
    command:
      - serve
    ports:
      - 25:25
      - 8888:80
    environment:
      - NTFY_WEB_ROOT=${WEB_ROOT}
      - TZ=${CONTAINER_TZ}
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_AUTH_FILE=/etc/ntfy/auth.db
      - NTFY_ENABLE_LOGIN=true
      - NTFY_CACHE_DURATION=12h
    user: 1000:1000
    volumes:
      - type: bind
        source: ./../Docker-data/Notifications/Ntfy/cache
        target: /var/cache/ntfy
      - type: bind
        source: ./../Docker-data/Notifications/Ntfy/data
        target: /etc/ntfy
    restart: unless-stopped