services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:main-ubuntu
    user: "0"
    networks:
      - proxy
    ports:
      - 3040:3000
    volumes:
      - type: bind
        source: ./../Docker-data/Monitoring/Grafana/data
        target: /var/lib/grafana
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./../Docker-data/Monitoring/Prometheus/data/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    networks:
      - proxy
  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:latest 
    container_name: cadvisor 
    restart: always
    ports:
      - 9111:8080
    volumes: 
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /sys
        target: /sys
        read_only: true
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
        read_only: true
      - type: bind
        source: /var/run
        target: /var/run
    devices:
      - /dev/kmsg:/dev/kmsg
    networks:
      - proxy
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: /
        target: /host
        read_only: true
        bind:
          propagation: rslave
    networks:
      - proxy

networks:
  proxy:
    external: true