services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
      - 9080:9080/tcp # Qbit
      - 9080:9080/udp # Qbit
      - 9696:9696/tcp # Prowlarr
      - 9696:9696/udp # Prowlarr
    volumes:
      - type: bind
        source: ./../Docker-data/Media/Gluetun/data
        target: /gluetun 
    networks:
      proxy:
      gluetun_network:
          ipv4_address: 172.16.100.10
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASS}
      - SERVER_REGIONS=${VPN_REGIONS}
      - TZ=${CONTAINER_TZ}
      - UPDATER_PERIOD=24h
      - VPN_PORT_FORWARDING=off
      - PORT_FORWARD_ONLY=false
      - FIREWALL_OUTBOUND_SUBNETS=${VPN_OUTBOUND_SUBNET}
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${CONTAINER_TZ}
      - WEBUI_PORTS=9080/tcp,9080/udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./../Docker-data/Media/Qbittorrent/config
        target: /config  
      - type: bind
        source: ./../Docker-data/Media/Media/Downloads
        target: /data/downloads
    
  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${CONTAINER_TZ}
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./../Docker-data/Media/Prowlarr/config
        target: /config  

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${CONTAINER_TZ}
    restart: unless-stopped
    networks:
      proxy:
      gluetun_network:
          ipv4_address: 172.16.100.20
    volumes:
      - type: bind
        source: ./../Docker-data/Media/Sonarr/config
        target: /config  
      - type: bind
        source: ./../Docker-data/Media/Media/TV
        target: /data/tv
      - type: bind
        source: ./../Docker-data/Media/Media/Movies
        target: /data/movies
      - type: bind
        source: ./../Docker-data/Media/Media/Downloads
        target: /data/downloads
  
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${CONTAINER_TZ}
    restart: unless-stopped
    networks:
      proxy:
      gluetun_network:
          ipv4_address: 172.16.100.30
    volumes:
      - type: bind
        source: ./../Docker-data/Media/Radarr/config
        target: /config  
      - type: bind
        source: ./../Docker-data/Media/Media/TV
        target: /data/tv
      - type: bind
        source: ./../Docker-data/Media/Media/Movies
        target: /data/movies
      - type: bind
        source: ./../Docker-data/Media/Media/Downloads
        target: /data/downloads
  
  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr:latest
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${CONTAINER_TZ}
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - type: bind
        source: ./../Docker-data/Media/Overseerr/config
        target: /config  
  
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - "8191:8191"
    networks:
      gluetun_network:
          ipv4_address: 172.16.100.40
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${CONTAINER_TZ}
    restart: unless-stopped
  
  plex:
    container_name: plex
    image: ghcr.io/hotio/plex
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${CONTAINER_TZ}
      - PLEX_CLAIM_TOKEN=${PLEX_CLAIM_TOKEN}
      - PLEX_BETA_INSTALL=false
      - PLEX_PURGE_CODECS=false
    networks:
      - proxy
    volumes:
      - type: bind
        source: ./../Docker-data/Media/Plex/transcode
        target: /transcode
      - type: bind
        source: ./../Docker-data/Media/Plex/config
        target: /config      
      - type: bind
        source: ./../Docker-data/Media/Media/TV
        target: /data/tv
      - type: bind
        source: ./../Docker-data/Media/Media/Movies
        target: /data/movies
  
  tautulli:
    container_name: tautulli
    image: ghcr.io/hotio/tautulli
    ports:
      - "8181:8181"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${CONTAINER_TZ}
      - WEBUI_PORTS=8181/tcp,8181/udp
    networks:
      - proxy
    volumes:
      - type: bind
        source: ./../Docker-data/Media/Tautulli/config
        target: /config
  
  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr
    ports:
      - "5056:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${CONTAINER_TZ}
    networks:
      - proxy
    volumes:
      - type: bind
        source: ./../Docker-data/Media/Jellyseerr/config
        target: /config
  
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    ports:
      - "8096:8096"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${CONTAINER_TZ}
    networks:
      - proxy
    volumes:
      - type: bind
        source: ./../Docker-data/Media/Media/TV
        target: /data/tv
      - type: bind
        source: ./../Docker-data/Media/Media/Movies
        target: /data/movies
      - type: bind
        source: ./../Docker-data/Media/Jellyfin/config
        target: /config

networks:
  gluetun_network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.100.0/24"
  proxy:
    external: true