services:
  folders-init:
    container_name: folders-init
    image: alpine
    restart: "no"
    entrypoint: '/bin/sh -c "chown 1000:1000 /data/*"'
    volumes:
      - ntfy-cache:/data/ntfy-cache
      - ntfy-data:/data/ntfy

  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy
    command:
      - serve
    networks:
      - proxy
    environment:
      - NTFY_BASE_URL=https://ntfy.${SERVER_DOMAIN}
      - NTFY_WEB_ROOT=${WEB_ROOT}
      - TZ=${CONTAINER_TZ}
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_ATTACHMENT_CACHE_DIR=/var/cache/ntfy/attachments
      - NTFY_AUTH_FILE=/etc/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_ENABLE_LOGIN=true
      - NTFY_UPSTREAM_BASE_URL=https://ntfy.sh
      - NTFY_CACHE_DURATION=0
      - NTFY_WEB_PUSH_FILE=/etc/ntfy/webpush.db
      - NTFY_WEB_PUSH_PUBLIC_KEY=${WEB_PUSH_PUBLIC_KEY}
      - NTFY_WEB_PUSH_PRIVATE_KEY=${WEB_PUSH_PRIVATE_KEY}
      - NTFY_WEB_PUSH_EMAIL_ADDRESS=${WEB_PUSH_EMAIL_ADDRESS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.rule=Host(`ntfy.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.ntfy.entrypoints=https"
      - "traefik.http.routers.ntfy.tls=true"
      - "traefik.http.services.ntfy.loadbalancer.server.port=80"
    user: 1000:1000
    env_file: Server.env
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-data:/etc/ntfy
    restart: unless-stopped
    depends_on:
      folders-init:
        condition: service_completed_successfully
  
volumes:
  ntfy-data:
    driver: local
  ntfy-cache:
    driver: local

networks:
  proxy:
    external: true