services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${CONTAINER_TZ}
    volumes:
      - type: bind
        source: /opt/homelab/Docker-data/Sync/Syncthing/config
        target: /config
      - type: bind
        source: /opt/homelab/Docker-data/Sync/Syncthing/data
        target: /data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing-secure.entrypoints=https"
      - "traefik.http.routers.syncthing-secure.rule=Host(`syncthing.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.syncthing-secure.tls=true"
      - "traefik.http.routers.syncthing-secure.service=syncthing"
      - "traefik.http.services.syncthing.loadbalancer.server.scheme=http" 
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true